import WeatherProvider from "@/context/WeatherContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <WeatherProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </WeatherProvider>
  )
}
