import NoteProvider from "@/context/NoteContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <NoteProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </NoteProvider>
  )
}
